### PR TITLE
Upgrade mastarm to v5 + upgrade deps

### PR DESCRIPTION
**Pull request by landonreed**
I noticed there were a bunch of security vulnerabilities for this repo, so I think bumping mastarm and upgrading deps should resolve many of them.

### CODE REVIEW

**Comment by evansiroky** [comment]
I'm a little on the fence about whether this should be considered a breaking change. If some people are using node 8, this would probably break things for them.

**Comment by landonreed** [comment]
Hmm, yea you're probably right. Shall I amend with `BREAKING`?

**Comment by evansiroky** [comment]
Yeah, that would be great.

**Comment by landonreed** [comment]
Actually, this would only break things for developers of the msr library, not users. Is that correct? If that is the case, I don't actually think this should be considered breaking.

**Comment by evansiroky** [comment]
Yeah, I guess you're right since there are no engines specified in the package.json.

**Comment by landonreed** [comment]
Sounds good. Once you approve, I'll go ahead and merge.

**Pull request merged**
