### PR TITLE
Support Maven wrapper script

### PR DESCRIPTION
**Pull request by KengoTODA**
Thanks for sharing great software that solves our common and huge problem :)
I'm trying to use this product that uses Maven wrapper, so I want to suggest you to check existence of `mvnw` script.

### CODE REVIEW

**Comment by evansiroky** [comment]
Ah interesting, I hadn't heard of Maven wrapper before, but see how this could be useful!

The code looks fine to me, but could you add a little sentence or two to the README about how Maven wrapper is used if it is available?

**Comment by KengoTODA** [comment]
Hi @evansiroky, thanks for your quick feedback! I made it at the end of README, please check.

**Comment by evansiroky** [comment]
Thanks for adding that! I'm going to merge this into our dev branch and make some really small grammar changes in the README. I'll try to have this released by the end of the week.

**Pull request merged**
